### ISSUE TITLE
Test runner fails with OOM

### ISSUE THREAD

**Issue by 0xE282B0** [exercism/cobol-test-runner#4]
Hi @ErikSchierboom,

I changed the logging so that in case no `test.cob` file is created, we see the complete log output.
It looks like cobolcheck is running out of memory. I never checked how much memory is consumed. The program is a Java app, which is built with GraalVM native image to a binary.

How much memory is allowed to consume?

```
Found cobolcheck, using ./bin/cobolcheck
Fatal error: unhandled exception in isolate 0x7f9775c00000: java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
    at com.oracle.svm.core.thread.PlatformThreads.startThread(PlatformThreads.java:674)
    at java.lang.Thread.start0(Thread.java:343)
    at java.lang.Thread.start(Thread.java:802)
    at com.oracle.svm.core.heap.ReferenceHandlerThread.start(ReferenceHandlerThread.java:54)
    at com.oracle.svm.core.graal.snippets.CEntryPointSnippets.initializeIsolate(CEntryPointSnippets.java:286)
    at com.oracle.svm.core.JavaMainWrapper$EnterCreateIsolateWithCArgumentsPrologue.enter(JavaMainWrapper.java:278)

```

**Comment by ErikSchierboom** [comment]
There should be lots (3GB IIRC). Any ideas @iHiD?

**Comment by iHiD** [comment]
This is the same error that the Java Test Runner had last week.

**Comment by 0xE282B0** [comment]
Does the host machine have a thread limit? (`ulimit -u`)
Is there anything we can do to solve that?

**Comment by KTSnowy** [comment]
@0xE282B0 Is there an option to limit the amount of memory used?

**Comment by KTSnowy** [comment]
I found the PR to fix the OOM error on the Java Test Runner exercism/java-test-runner#53 that @iHiD mentioned. Maybe we could try the same fix and see if it also works for us?

**Comment by KTSnowy** [comment]
Ubuntu 22.04 seems to be the cause of the issue? 
adoptium/temurin-build#2974
flyway/flyway#3457

**Comment by KTSnowy** [comment]
> test.cob: 190: warning: ignoring redundant .\ntest.cob: 192: warning: ignoring redundant .\ntest.cob: 194: warning: ignoring redundant .\ntest.cob: 435: warning: ignoring redundant .\ntest.cob: 436: warning: ignoring redundant

**Comment by KTSnowy** [comment]
![Screen Shot 2022-07-27 at 16 05 49](https://user-images.githubusercontent.com/73310001/181352285-7cfd96f9-0cf4-4efa-8daa-1062761f0c91.png)

@0xE282B0 It's working now?

**Comment by KTSnowy** [comment]
![Screen Shot 2022-07-27 at 16 07 26](https://user-images.githubusercontent.com/73310001/181352592-60b3c3d2-6826-4d06-81a7-846a03efa3b0.png)

The tests are running now, it just has a lot of "Ignoring redundant" at the top. But it's working 😃

**Comment by ErikSchierboom** [comment]
Yay! 🥳 I could get `leap` passing.

**Comment by KTSnowy** [comment]
IT'S WORKING! 😀

**Comment by KTSnowy** [comment]
![Screen Shot 2022-07-27 at 16 16 10](https://user-images.githubusercontent.com/73310001/181353971-708e30f1-6e11-461e-8f3d-87f740bf6694.png)
Hey @ErikSchierboom do you know what could be the cause of this issue?

**Comment by ErikSchierboom** [comment]
@KTSnowy I don't, but I'll look into it.

**Comment by 0xE282B0** [comment]
Funny thing!
@ErikSchierboom, I thought that a failing test would block the deployment.
@KTSnowy The test is failing because ububtu20.04 only has gnuCobol 2.2 in its repos.
I'll fix that by installing it manually.

**Comment by ErikSchierboom** [comment]
@0xE282B0 No, those are two unrelated things. The idea is that no PR can be merged if the tests are failing, but this looks to not have been the case.

**Comment by 0xE282B0** [comment]
Yes that's true. If I had done it right it would not have been merged. 😖

**Comment by KTSnowy** [comment]
> @KTSnowy The test is failing because ububtu20.04 only has gnuCobol 2.2 in its repos.

You mean the "Ignoring Redundant" messages?

**Comment by KTSnowy** [comment]
Also, I'm having an issue with the Raindrops exercises, it says that "fetch-cobolcheck: line 42: curl: command not found" exercism/cobol#54

**Comment by 0xE282B0** [comment]
@KTSnowy that means the `test.sh` is not the latest, can you replace it with the one from `leap`?

**Comment by KTSnowy** [comment]
I'll replace it and open a PR for it

**Comment by 0xE282B0** [comment]
And old versions of the exercises are failing for me but that should be resolved as soon as it is possible to update the exercises.

**Comment by KTSnowy** [comment]
@0xE282B0 exercism/cobol#55

I'm also having issues updating the exercises right now. Did we break something?

**Comment by KTSnowy** [comment]
@0xE282B0 I was able to update the Raindrops exercise files, but still not able to update the Hamming Distance exercise. I have a feeling that something might be wrong in the Hamming Distance files.

**Comment by 0xE282B0** [comment]
I can't update hello-world and leap:
<img width="602" alt="image" src="https://user-images.githubusercontent.com/4034494/181359515-026a0b92-780a-47f4-a402-61d8f8fa71e7.png">

@ErikSchierboom do we just need to change something in the exercise to resolve the update problem?
Raindrops which we just changed can be updated for me.

**Comment by KTSnowy** [comment]
@0xE282B0 The CI checks on the track repo seem to be stuck? The one we merged is still "running" for me.

**Comment by KTSnowy** [comment]
![Screen Shot 2022-07-27 at 17 05 45](https://user-images.githubusercontent.com/73310001/181362290-36790b6b-5ef6-48e6-90fc-f28a5d7476b4.png)

**Comment by iHiD** [comment]
Hi everyone. **Could we please keep one issue for each thing that needs dealing with.** Currently this Issue has a whole load of different discussions which make it very hard to keep up with or understand what is going on. e.g. the OOM memory error, the file updating, CI on the tracks. Each of these separate things needs to have a separate issue opening for it and the relevant member of the team requested for attention. Free flowing discussions should occur on Slack.

Also, please note that the CI on the cobol track has nothing to do with the out of memory issue in the test runner. The CI on the track and the test-runner are entirely separate things.

Thank you.

**Comment by KTSnowy** [comment]
@iHiD Sorry. Since the OOM issue has been fixed, we should close this issue for now.

**Comment by iHiD** [comment]
No probs. Thanks!
